### ISSUE TITLE
2k屏幕下 百度搜索的居中偏离

### ISSUE THREAD

**Issue by God-JohnDiamond** [qxinGitHub/searchEngineJump#122]

**Comment by CDJenson** [comment]
![image](https://user-images.githubusercontent.com/22700161/204025649-e91fbc80-7bfe-44ce-b726-949ea8999379.png)
是的

**Comment by lqzhgood** [comment]
百度的写法是
```css
@media screen and (min-width: 1921px)
#container.sam_newgrid {
    margin: 0 auto;
    width: 1088px;
    padding-left: 158px; 
    box-sizing: content-box;
}
```

不知道插件里面 `@media` 查询怎么写
